[package]
authors.workspace      = true
description            = "IndexedDB-backed Store implementation for miden-client (WASM)"
edition.workspace      = true
license.workspace      = true
name                   = "miden-idxdb-store"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lib]
crate-type = ["cdylib", "rlib"]
doctest    = false
test       = false

[dependencies]
# Miden dependencies
miden-client = { workspace = true }

# Workspace dependencies
async-trait = { workspace = true }
chrono      = { workspace = true }
serde       = { features = ["derive"], workspace = true }

# External dependencies
base64               = { version = "0.22" }
serde-wasm-bindgen   = { workspace = true }
wasm-bindgen         = { features = ["serde-serialize"], workspace = true }
wasm-bindgen-futures = { workspace = true }

[lints]
workspace = true
