name: Deploy wallet example

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: |
            packages/react-sdk/yarn.lock
            packages/react-sdk/examples/wallet/yarn.lock
      - name: Install root dependencies
        run: yarn install --frozen-lockfile
      - name: Build react sdk
        working-directory: packages/react-sdk
        run: yarn build
      - name: Install wallet dependencies
        working-directory: packages/react-sdk/examples/wallet
        run: yarn install --frozen-lockfile
      - name: Build wallet example
        working-directory: packages/react-sdk/examples/wallet
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: yarn build --base="/$REPO_NAME/wallet-react-example/" --outDir=dist/wallet-react-example
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: packages/react-sdk/examples/wallet/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
