name: Web Client Docs

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read

jobs:
  docs-check:
    name: Check that web client documentation is up-to-date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false


      - name: Check for bypass label
        if: github.event_name == 'pull_request'
        id: bypass
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            core.setOutput('skip', labels.includes('bypass-sdk-version-bump'));

      - name: Install Rust toolchain
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        run: rustup update --no-self-update

      - name: Setup Node.js
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '20'

      - name: Add WASM target
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        run: rustup target add wasm32-unknown-unknown

      - name: Install Dependencies
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        run: ./scripts/retry-yarn-install.sh crates/web-client

      - name: Build Project
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        working-directory: crates/web-client
        run: yarn build

      - name: Generate Documentation
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        working-directory: crates/web-client
        run: yarn typedoc

      - name: Verify Documentation is Up-to-date
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        run: git diff --exit-code docs/typedoc/web-client
